services:
  bob:
    build: .
    volumes:
      - ./web/db.sqlite3:/web/db.sqlite3
      - /sys:/sys  # For GPIO pin access
      - /sys/firmware/devicetree/base/model:/model # For checking platform
    privileged: true  # For GPIO pin access
    devices:
      - "/dev/gpiomem:/dev/gpiomem"  # For GPIO pin access
    restart: always
    environment:
      COMMIT_MESSAGE: ${COMMIT_MESSAGE}
      COMMIT_AUTHOR_NAME: ${COMMIT_AUTHOR_NAME}
      COMMIT_AUTHOR_EMAIL: ${COMMIT_AUTHOR_EMAIL}
      BOT_TOKEN: ${BOT_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TG_CLIENT_API_ID: ${TG_CLIENT_API_ID}
      TG_CLIENT_API_HASH: ${TG_CLIENT_API_HASH}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      ENTSOE_API_KEY: ${ENTSOE_API_KEY}
  web:
    build: .
    volumes:
      - ./web/db.sqlite3:/web/db.sqlite3
    restart: always
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    expose:
      - "8000"
    ports:
      - "8000:8000"
    working_dir: /
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
