version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  bob:
    build: .
    command: python bob/main.py
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
# web:
#   build: .
#   command: python web/manage.py runserver 0.0.0.0:8000
#   volumes:
#     - .:/code
#   ports:
#     - "8080:8080"
#   environment:
#     - POSTGRES_NAME=postgres
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=postgres
#   depends_on:
#     - db
