version: "3.9"

services:
  bob:
    build: .
    volumes:
      - ./web/db.sqlite3:/web/db.sqlite3
    restart: always
    environment:
      COMMIT_MESSAGE: ${COMMIT_MESSAGE}
      COMMIT_AUTHOR_NAME: ${COMMIT_AUTHOR_NAME}
      COMMIT_AUTHOR_EMAIL: ${COMMIT_AUTHOR_EMAIL}
      BOT_TOKEN: ${BOT_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
  web:
    build: .
    volumes:
      - ./web/db.sqlite3:/web/db.sqlite3
      - ./web/staticfiles:/web/staticfiles
    restart: always
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    expose:
      - "8000"
    working_dir: /web
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000

  nginx:
    build: ./nginx
    volumes:
      - ./web/staticfiles:/web/staticfiles
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
