version: "3.9"

services:
  bob:
    build: .
    volumes:
      - ./web/db.sqlite3:/web/db.sqlite3
    restart: always
    environment:
      COMMIT_MESSAGE: ${COMMIT_MESSAGE}
      COMMIT_AUTHOR_NAME: ${COMMIT_AUTHOR_NAME}
      COMMIT_AUTHOR_EMAIL: ${COMMIT_AUTHOR_EMAIL}
# web:
#   build: .
#   command: python web/manage.py runserver 0.0.0.0:8000
#   volumes:
#     - ./web/db.sqlite3:/web/db.sqlite3
#   ports:
#     - "8080:8080"
